import { expect, test } from '@playwright/test'

test('avalanche puts higher APR debt first in payoff order', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('add-debt').click()
  await page.getByTestId('add-debt').click()
  const cards = page.locator('.loan-card')
  const first = cards.nth(0)
  const second = cards.nth(1)
  await first.locator('[data-testid^="details-"]').click()
  await second.locator('[data-testid^="details-"]').click()

  await first.locator('.name-input').fill('Debt A')
  await second.locator('.name-input').fill('Debt B')
  await first.locator('label:has-text("Остаток") input').fill('500000')
  await second.locator('label:has-text("Остаток") input').fill('100000')
  await first.locator('label:has-text("%") input').fill('10')
  await second.locator('label:has-text("%") input').fill('30')
  await first.locator('label:has-text("Срок (месяцы)") input').fill('60')
  await second.locator('label:has-text("Срок (месяцы)") input').fill('60')
  await first.locator('label:has-text("Платёж") input').fill('15000')
  await second.locator('label:has-text("Платёж") input').fill('5000')
  await first.locator('label:has-text("Дата платежа") input').fill('2026-02-10')
  await second.locator('label:has-text("Дата платежа") input').fill('2026-02-10')
  await page.getByTestId('strategy-select').selectOption('avalanche')
  await page.getByTestId('calculate-plan').click()
  await expect(page.locator('.errors')).toHaveCount(0)

  await expect(page.getByTestId('payoff-order').locator('li').first()).toContainText('Debt B')
})

test('snowball puts lower balance debt first in payoff order', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('add-debt').click()
  await page.getByTestId('add-debt').click()
  const cards = page.locator('.loan-card')
  const first = cards.nth(0)
  const second = cards.nth(1)
  await first.locator('[data-testid^="details-"]').click()
  await second.locator('[data-testid^="details-"]').click()

  await first.locator('.name-input').fill('Big Debt')
  await second.locator('.name-input').fill('Small Debt')
  await first.locator('label:has-text("Остаток") input').fill('800000')
  await second.locator('label:has-text("Остаток") input').fill('120000')
  await first.locator('label:has-text("Срок (месяцы)") input').fill('60')
  await second.locator('label:has-text("Срок (месяцы)") input').fill('60')
  await first.locator('label:has-text("%") input').fill('12')
  await second.locator('label:has-text("%") input').fill('5')
  await first.locator('label:has-text("Платёж") input').fill('20000')
  await second.locator('label:has-text("Платёж") input').fill('5000')
  await first.locator('label:has-text("Дата платежа") input').fill('2026-02-10')
  await second.locator('label:has-text("Дата платежа") input').fill('2026-02-10')
  await page.getByTestId('strategy-select').selectOption('snowball')
  await page.getByTestId('calculate-plan').click()
  await expect(page.locator('.errors')).toHaveCount(0)

  await expect(page.getByTestId('payoff-order').locator('li').first()).toContainText('Small Debt')
})

test('includeInPlan=false keeps loan in list but removes it from strategy focus', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('add-debt').click()
  await page.getByTestId('add-debt').click()
  const cards = page.locator('.loan-card')
  const first = cards.nth(0)
  const second = cards.nth(1)
  await first.locator('[data-testid^="details-"]').click()
  await second.locator('[data-testid^="details-"]').click()

  await first.locator('.name-input').fill('Excluded High APR')
  await second.locator('.name-input').fill('Included Loan')
  await first.locator('label:has-text("Остаток") input').fill('100000')
  await second.locator('label:has-text("Остаток") input').fill('120000')
  await first.locator('label:has-text("%") input').fill('60')
  await second.locator('label:has-text("%") input').fill('10')
  await first.locator('label:has-text("Срок (месяцы)") input').fill('60')
  await second.locator('label:has-text("Срок (месяцы)") input').fill('60')
  await first.locator('label:has-text("Платёж") input').fill('8000')
  await second.locator('label:has-text("Платёж") input').fill('8000')
  await first.locator('label:has-text("Дата платежа") input').fill('2026-02-10')
  await second.locator('label:has-text("Дата платежа") input').fill('2026-02-10')
  await first.locator('input[type="checkbox"]').uncheck()
  await page.getByTestId('strategy-select').selectOption('avalanche')
  await page.getByTestId('calculate-plan').click()
  await expect(page.locator('.errors')).toHaveCount(0)

  await expect(page.getByTestId('focus-badge')).toContainText('Included Loan')
  await expect(cards).toHaveCount(2)
})

test('loan details show portfolio plan schedule after calculation', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('add-debt').click()
  const firstCard = page.locator('.loan-card').nth(0)

  await firstCard.locator('.name-input').fill('Detail Loan')
  await firstCard.locator('[data-testid^="details-"]').click()
  await firstCard.locator('label:has-text("Остаток") input').fill('200000')
  await firstCard.locator('label:has-text("%") input').fill('12')
  await firstCard.locator('label:has-text("Срок (месяцы)") input').fill('60')
  await firstCard.locator('label:has-text("Платёж") input').fill('10000')
  await firstCard.locator('label:has-text("Дата платежа") input').fill('2026-02-10')
  await page.getByTestId('extra-budget').fill('9000')
  await page.getByTestId('calculate-plan').click()
  await expect(page.locator('.errors')).toHaveCount(0)

  const table = firstCard.locator('table')
  await expect(table).toBeVisible()
})
